USE cinema_booking;

CREATE TABLE IF NOT EXISTS user_vouchers (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  promotion_id BIGINT NOT NULL,
  code VARCHAR(50) NOT NULL,
  discount_amount INT NOT NULL,
  points_cost INT NOT NULL DEFAULT 0,
  status ENUM('AVAILABLE','RESERVED','USED') NOT NULL DEFAULT 'AVAILABLE',
  booking_id BIGINT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  reserved_at TIMESTAMP NULL,
  expires_at DATETIME NULL,
  source ENUM('POINT_EXCHANGE','ADMIN_GIFT') NOT NULL DEFAULT 'POINT_EXCHANGE',
  target_tier_id INT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (promotion_id) REFERENCES promotions(id) ON DELETE CASCADE,
  FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE SET NULL,
  FOREIGN KEY (target_tier_id) REFERENCES membership_tiers(id) ON DELETE SET NULL
);

CREATE INDEX idx_user_vouchers_promotion ON user_vouchers(promotion_id);
CREATE INDEX idx_user_vouchers_code ON user_vouchers(code);

ALTER TABLE user_vouchers
  MODIFY status ENUM('AVAILABLE','RESERVED','USED') NOT NULL DEFAULT 'AVAILABLE';

ALTER TABLE user_vouchers
  ADD COLUMN IF NOT EXISTS expires_at DATETIME NULL;

ALTER TABLE user_vouchers
  ADD COLUMN IF NOT EXISTS source ENUM('POINT_EXCHANGE','ADMIN_GIFT') NOT NULL DEFAULT 'POINT_EXCHANGE';

ALTER TABLE user_vouchers
  ADD COLUMN IF NOT EXISTS target_tier_id INT NULL;

CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  title VARCHAR(150) NOT NULL,
  message TEXT NOT NULL,
  type VARCHAR(40) NOT NULL DEFAULT 'INFO',
  payload JSON NULL,
  is_read BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
